client_config_backend: settings
client_config:
  client_id: 1057452086139-l826rkv8n8nsmubvt9t8ha7fnjd4ogms.apps.googleusercontent.com
  client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials_module.json

get_refresh_token: True

oauth_scope:
  - https://www.googleapis.com/auth/drive